services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER} # Set the PostgreSQL user
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Set the PostgreSQL password
      POSTGRES_DB: ${DB_NAME} # Set the database name
    ports:
      - '5434:5432'
  test-db:
    image: postgres:16
    container_name: postgres-test-db
    environment:
      POSTGRES_USER: ${DB_USER} # Set the PostgreSQL user
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Set the PostgreSQL password
      POSTGRES_DB: ${DB_NAME} # Set the database name
    ports:
      - '5435:5432'
